fixtures:
  repositories:
    "augeasproviders": "git://github.com/domcleal/augeasproviders.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "ssh": "#{source_dir}"
